### ISSUE TITLE
Turning off account filter breaks the drop down form field

### ISSUE THREAD

**Issue by adsuttie** [Bwian/pops#133] opened 2015-08-28 00:21 UTC
The accounts field works well with the filters on. Turning the filter off causes the field to fail. The problem does not appear to happen on the Program field.

**Comment by Bwian** [comment] 2015-08-28 01:06
Causes the field to fail how?

On 28/08/2015 10:21 am, "adsuttie" <notifications@github.com> wrote:


The accounts field works well with the filters on. Turning the filter off
causes the field to fail. The problem does not appear to happen on the
Program field.


Reply to this email directly or view it on GitHub
<https://github.com/Bwian/pops/issues/133> .

**Comment by adsuttie** [comment] 2015-08-28 02:40
Demonstration via this video. The field is just blank and there is nothing to select.
http://screencast-o-matic.com/watch/cojunAfpTi

**Comment by Bwian** [comment] 2015-08-30 11:03
This was caused by a debug statement left in the controller.  Should be fixed now.

**Closed by Bwian** 2015-08-30 11:03 UTC
Labels: Bug
